### PR TITLE
Add json-body function

### PR DESCRIPTION
**Pull request by morganastra**
New PR from the discussion on #7, as requested

### CODE REVIEW

**Comment by morganastra** [comment]
oops, the test fails due to the non-deterministic ordering of map keys. let me figure out a way around that.

**Comment by weavejester** [comment]
Thanks for the patch. I think I'd prefer Cheshire over data.json, as that's what ring-json currently uses. Can you also squash your commits and capitalize the first letter so that they're consistent with the repository history?

**Comment by morganastra** [comment]
yep, all done

**Comment by morganastra** [comment]
Is there anything else we need to do for this?

**Comment by weavejester** [comment]
Nope, that looks fine. Sorry about the delay in getting round to merging this.

**Pull request merged**
