### PR TITLE
Default port should be 443 when scheme is :https

### LINKED ISSUE #3: Default port should be 443 when scheme is :https
Originally opened as weavejester/ring-mock#15

### PR DESCRIPTION
**Pull request by lvh**
Closes #3.

### CODE REVIEW

**Comment by lvh** [comment]
Ack! Apparently `some?` is new in 1.6. Depending on the resolution of #4 (i.e. if we upgrade the listed Clojure dependency or not) this will either start passing after we upgrade and I forward merge this, or I downgrade this to say `(not (nil? x))` instead. I'd prefer not to do that right now, as I believe `some?` to be the idiomatic spelling.

**Comment by lvh** [comment]
Alternatively:

```clojure
(or port (condp = scheme :http 80 :https 443))
```

... of course.

**Comment by weavejester** [comment]
You don't need to use `(not (nil? x))`. You can just use `x` as long as you don't need to distinguish between `false` and `nil`.

I think I'd prefer that you define a map of default ports, e.g.

```clojure
(def default-scheme-port {:http 80, :https 443})
```

Then set the port as:

```clojure
(or port (default-scheme-port scheme))
```

It might also be better to get the scheme as:

```clojure
(keyword (or (.getScheme uri) "http"))
```

As that way we're not calling `(keyword nil)` at any point. It apparently works, but I don't know whether that's intentional or not.

**Comment by weavejester** [comment]
Thanks. Could you squash your commits?

**Comment by lvh** [comment]
Done.

**Comment by weavejester** [comment]
Could you change the commit message to imperative mood, e.g. something like:

    Set default port to 443 when scheme is :https (fixes #3)

**Comment by lvh** [comment]
Done.

**Comment by weavejester** [comment]
Perfect. Thanks!

**Pull request merged**
